Add error detection and reporting.

diff --git a/Templates/basic_handle/test b/Templates/basic_handle/test
--- a/Templates/basic_handle/test
+++ b/Templates/basic_handle/test
@@ -3,3 +3,6 @@
 enable -f ./TEMPLATE.so TEMPLATE
 
 TEMPLATE "${@:1}"
+if [ "$?" -ne 0 ]; then
+    echo "TEMPLATE failed: $TEMPLATE_ERROR"
+fi
